[server]
url = "http://127.0.0.1:8081"
cert = "tls/cert.pem"
key = "tls/key.pem"

[log]
actix-web = "debug"
webapp = "trace"

[mongodb]
host = "127.0.0.1"
username = "username"
password = ""
database = "database"