[package]
name = "hope_library"
version = "0.1.1"
authors = ["Georg Bramm <georg.bramm@aisec.fraunhofer.de>"]
edition = "2018"
description = "A Rust implementation of the ehOPE encryption scheme"
keywords = [
  "paillier",
  "elgamal",
  "cryptography",
  "homomorphic-encrypt",
  "secure-computation",
]
homepage = "https://github.com/georgbramm/rust-hope"
repository = "https://github.com/georgbramm/rust-hope"
# documentation = "https://docs.rs/rust-hope"
license = "MIT/Apache-2.0"
categories = ["cryptography"]

[badges] 
travis-ci = { repository = "https://github.com/georgbramm/rust-hope" }
gitlab = { repository = "...", branch = "master" }

[dependencies] 

env_logger = "0.6"
serde = "1.0.16"
serde_json = "1.0.4"
serde_derive = "1.0.16"
getrandom = { version = "0.1", features = ["stdweb"] }
uuid = { version = "0.8", features = ["serde", "v4", "stdweb"] }
bn = { path = "../bn" }
hope = { version = "1.0.0", path = ".." }